{
  "hash": "c597c801f8ff3e8eee0b7cc4a15d2c10",
  "result": {
    "engine": "knitr",
    "markdown": "---\nembed-resources: true\n---\n\n\n\n\n# Communicating Research with Quarto\n\n## Introduction\n\nQuarto provides a unified authoring framework for data science, combining your code, its results, and your prose. Quarto documents are fully reproducible and support dozens of output formats, like PDFs, Word files, presentations, and more.\n\n![](images/quarto_hex.png){fig-align=\"center\" width=\"100\"}\n\nQuarto files are designed to be used in three ways:\n\n1.  For communicating to decision-makers, who want to focus on the conclusions, not the code behind the analysis.\n2.  For collaborating with other data scientists (including future you!), who are interested in both your conclusions, and how you reached them (i.e. the code).\n3.  As an environment in which to do data science, as a modern-day lab notebook where you can capture not only what you did, but also what you were thinking.\n\nQuarto is a command line interface tool, not an R package. This means that help is, by-and-large, not available through ?. Instead, as you work through this chapter, and use Quarto in the future, you should refer to the Quarto documentation (https://quarto.org/).\n\n![](images/quarto_1.png){fig-align=\"center\" width=\"400\"}\n\n*Note*\n\n*Quarto documents are fully reproducible and support dozens of output formats, like PDFs, Word files, slideshows, and more.*\n\n*Need some help?*\n\n-   Download Quarto: *https://quarto.org/docs/get-started/*\n\n-   Quarto Guide: *https://quarto.org/docs/guide/*\n\n-   Markdown Reference Sheet: *Help \\> Markdown Quick Reference*\n\nYou'll need the Quarto Command Line Interface but it is automatically done by RStudio for you.\n\nLet us create one from RStudio now.\n\nTo create a new Quarto document (`.qmd`), select *File -\\> New File -\\> Quarto Document* in RStudio, then choose the file type you want to create. For now we will focus on a `.html` Document, which can be easily converted to other file types later.\n\nGo ahead and give a title.\n\nThe newly created `.qmd` file comes with basic instructions, let us go through it now.\n\nIt contains three important types of content:\n\n-   An (optional) YAML header surrounded by `---`\n-   Chunks of R code surrounded by ```` ``` ````\n-   Text mixed with formatting like `##` headings and simple text.\n\n*YAML stands for yet another markup language or YAML ain't markup language (a recursive acronym), which emphasizes that YAML is for data, not documents.*\n\nIn any case, it holds the metadata of the document and can be really helpful.\n\n## How does Quarto work?\n\nWhen you render a Quarto document, first knitr executes all of the code chunks and creates a new markdown (`.md`) document, which includes the code and its output. The markdown file generated is then processed by pandoc, which creates the finished format. The Render button encapsulates these actions and executes them in the right order for you.\n\n![](images/quarto_2.png){fig-align=\"center\" width=\"400\"}\n\n## Some Basics of the Markdown syntax\n\nLearn more about Markdown from the Guide: https://quarto.org/docs/authoring/markdown-basics.html\n\n\\bigskip\n\nWhen you open an `.qmd`, you get a notebook interface where code and output are interleaved. You can run each code chunk by clicking the Run icon (it looks like a play button at the top of the chunk), or by pressing `Ctrl + Shift + Enter`.\n\n\\bigskip\n\nRStudio executes the code and displays the results inline with the code by default. However, you can change it to display in the console instead by clicking on the gear icon and changing the *Chunk Output in Console* option.\n\n![Basic Markdown Syntax and its output](images/basics_markdown_syntax.png){fig-align=\"center\" width=\"400\"}\n\n![](images/qmd_output_options.png){fig-align=\"center\" width=\"160\"}\n\nYou can *render* the entire document with a single click of a button.\n\nGo ahead and give it a try. RStudio might prompt you to save the document first, save it in your working directory by giving it a suitable title.\n\nYou should now see some output like this:\n\n![HTML output of the QMD file](images/default_qmd_output.png){fig-align=\"center\" width=\"350\"}\n\n## Code Chunks\n\nThe knitr package extends the basic markdown syntax to include chunks of executable R code.\n\nWhen you render the report, knitr will run the code and add the results to the output file. You can have the output display just the code, just the results, or both.\n\nTo embed a chunk of R code into your report, surround the code with two lines that each contain three back ticks. After the first set of backticks, include {r}, which alerts knitr that you have included a chunk of R code. The result will look like this:\n\n![R Code Chunk](images/rchunk1.JPG){fig-align=\"center\" width=\"300\"}\n\nTo omit the results from your final report (and not run the code) add the argument `eval = FALSE` inside the brackets and after `r`. This will place a copy of your code into the report.\n\n![R Code Chunk with \\`eval\\` set to FALSE](images/rchunk2.JPG){fig-align=\"center\" width=\"300\"}\n\nTo omit the code from the final report (while including the results) add the argument `echo = FALSE`. This is very handy for adding plots to a report, since you usually do not want to see the code that generates the plot.\n\n![R Code Chunk with \\`echo\\` set to FALSE](images/rchunk3.JPG){fig-align=\"center\" width=\"300\"}\n\nRead more about R Code Chunks at <https://rmarkdown.rstudio.com/articles_intro.html>. You can also change this from the gear icon on the right of the code chunk\n\n### Inline R Code\n\nYou can also evaluate R expressions inline by enclosing the expression within a single back-tick qualified with `r`.\n\n`knitr` will replace the inline code with its result in your final document (inline code is always replaced by its result). The result will appear as if it were part of the original text. For example, the snippet above will appear like this:\n\n![Inline R code in RMarkdown documents](images/inline.JPG){fig-align=\"center\" width=\"300\"}\n\n![HTML output of the QMD file](images/default_qmd_output_1.png){fig-align=\"center\" width=\"400\"}\n\nNow let us try building our own `.qmd` document and add our own analysis. Let us use a new dataset for this purpose. So go ahead and delete everything below the YAML header.\n\n> The data we are going to use today is the data of deaths due to COVID-19 in Kerala state. This information is available from the Government of Kerala COVID-19 Dashboard <https://dashboard.kerala.gov.in/covid/>\n\nLets begin!\n\nWorkflow with Quarto\n\nCreate a new project and open a new `.qmd` file in the project.  \n\n\n\n\n\n\n\n\n\n\n\nLoad Packages\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(rio)\n```\n:::\n\n\n\n\nLoad the Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- rio::import(\n  here(\"data\", \n    \"GoK Dashboard  Official Kerala COVID-19 Statistics.xlsx\"),\n                       skip = 1)\n```\n:::\n\n\n\n\nCheck the dimensions of the data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> dim()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21820     9\n```\n\n\n:::\n:::\n\n\n\n\nYou can alternatively use `nrow()` and `ncol()`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21820\n```\n\n\n:::\n\n```{.r .cell-code}\nmortality_df |> ncol()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n:::\n\n\n\n\nNow try to use them in the R inline code.\n\n\n\nHint: Use `` `r ` `` for inline code chunk like we discussed earlier. Inline R code chunks can be very useful when you are working with data.\n\n\nText in Quarto:\n\n\n\n\n::: {.cell}\n\n```{.md .cell-code}\nThere are `r mortality_df |> nrow()` rows in the data \nand `r mortality_df |> ncol()` columns.\n```\n:::\n\n\n\n\nOutput:\n\nThere are  21820 rows in the data and 9 columns.\n\nCheck the variable names and clean them\n\nA good practice is to first check all the variable names and clean them using the `clean_names()` function from the `janitor` package\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> names()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"SL No.\"                      \"Date Reported\"              \n[3] \"District\"                    \"Name\"                       \n[5] \"Place\"                       \"Age\"                        \n[7] \"Sex\"                         \"Date of death\"              \n[9] \"History(Traveler / contact)\"\n```\n\n\n:::\n:::\n\n\n\n\nLook at the difference in the `names()` of the dataset once it has been cleaned by `janitor`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> janitor::clean_names() |>  names()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sl_no\"                    \"date_reported\"           \n[3] \"district\"                 \"name\"                    \n[5] \"place\"                    \"age\"                     \n[7] \"sex\"                      \"date_of_death\"           \n[9] \"history_traveler_contact\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskimr::skim(mortality_df)\n```\n:::\n\n\n\n\nThe `skim()` function shows that `date_reported`, `date_death`, and `sex` are `character` variables which might not be ideal. Let us transform them into the data types `date` and `factor`. also that `history_traveler_contact` are mostly `NA`.\n\nLet us drop the column  `history_traveler_contact`, `name` and `place` from our analysis\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- mortality_df |> \n  select(-c(history_traveler_contact, name, place))\n```\n:::\n\n\n\n\n\nLets check the class of `date_reported`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> pull(date_reported) |> class()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n\nLets do some more cleaning of the variables\n\n\nWhen working with dates, the `lubridate` package is ideal. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate)\nmortality_df <- mortality_df |> \n  mutate(date_reported = lubridate::dmy(date_reported))\n```\n:::\n\n\n\n\nLets check the class of `date_reported` now\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> \n  pull(date_reported) |> \n  class()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\n*`pull()` is an excellent funtion that lets you pull a single varible from a dataset and perform operations. Read more about `pull()` in the Help menu.*\n\n\nLet us now look at the `sex` variable.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> \n  pull(sex) |>\n  unique()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Male\"   \"Female\" \"Others\" \"-\"      \"gf\"     \"male\"   NA      \n```\n\n\n:::\n:::\n\n\n\n\nAfter some `mutate()` magic...\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> \n  mutate(sex = fct_collapse(sex, Male = \"male\")) |> \n  pull(sex) |> \n  unique()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Male   Female Others -      gf     <NA>  \nLevels: - Female gf Male Others\n```\n\n\n:::\n:::\n\n\n\n\n\nWe can pipe multiple mutate() functions too..\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- mortality_df |> \n  mutate(date_of_death = lubridate::dmy(date_of_death)) |> \n  mutate(sex = fct_collapse(sex, Male = \"male\")) |> \n  mutate(sex = factor(sex, levels = c(\"Male\", \"Female\")))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `mutate()`.\nℹ In argument: `date_of_death = lubridate::dmy(date_of_death)`.\nCaused by warning:\n!  47 failed to parse.\n```\n\n\n:::\n:::\n\n\n\n\nLet us `drop_na()` for now\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- mortality_df |> drop_na()\n```\n:::\n\n\n\n\nLet us look at the number of rows now\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n mortality_df |> nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21609\n```\n\n\n:::\n:::\n\n\n\n\nLet us look at the Districts \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> pull(district) |> unique() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Thiruvananthapuram\"   \"Kollam\"               \"Pathanamthitta\"      \n [4] \"Kottayam\"             \"Idukki\"               \"Ernakulam\"           \n [7] \"Thrissur\"             \"Palakkad\"             \"Malappuram\"          \n[10] \"Kozhikode\"            \"Wayanad\"              \"Kasaragod\"           \n[13] \"Alappuzha\"            \"Kannur\"               \"Thiruvananthapura m\" \n[16] \"THIRUVANANTHAPURAM\"   \"KOLLAM\"               \"PATHANAMTHITTA\"      \n[19] \"ALAPPUZHA\"            \"KOTTAYAM\"             \"IDUKKI\"              \n[22] \"ERNAKULAM\"            \"THRISSUR\"             \"PALAKKAD\"            \n[25] \"MALAPPURAM\"           \"KOZHIKODE\"            \"WAYANAD\"             \n[28] \"KANNUR\"               \"KASARAGOD\"            \"Kasargod\"            \n[31] \"Thiruvananthapuram?K\" \"Alappuzha?Kannur\"     \"Kollam?Thiruvanantha\"\n[34] \"Malappuaram\"          \"Kozhikode?Thiruvanan\" \"Kozhikode?Ernakulam\" \n[37] \"Eranakulam\"          \n```\n\n\n:::\n:::\n\n\n\n\nLet us clean it\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- mortality_df |> \n mutate(district = str_to_sentence(district)) |> \n  mutate(district = fct_collapse(district,\n                                 Thiruvananthapuram = c(\n                                   \"Thiruvananthapura m\",\n                                   \"Thiruvananthapuram?K\"))) |> \n  mutate(district = fct_collapse(district, \n                                 Kollam = c(\n                                   \"Kollam?Thiruvanantha\"))) |> \n  mutate(district = fct_collapse(district, \n                                 Ernakulam = c(\n                                   \"Eranakulam\"))) |> \n  mutate(district = fct_collapse(district, \n                                 Kasaragod = c(\n                                   \"Kasargod\"))) |> \n  mutate(district = fct_collapse(district, \n                                 Kozhikode = c(\n                                   \"Kozhikode?Ernakulam\", \n                                   \"Kozhikode?Thiruvanan\"))) |> \n  mutate(district = fct_collapse(district, \n                                 Alappuzha = c(\n                                   \"Alappuzha?Kannur\"))) |> \n  mutate(district = fct_collapse(district, \n                                 Malappuram = c(\n                                   \"Malappuaram\"))) \n```\n:::\n\n\n\n\n\nLet us look at the number of Districts now\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> pull(district) |> unique() |> length()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\n\n\nLet us now create a new variable called `wave`. This will tell us if the death has happened in the first wave or second wave of COVID-19.\n\nFor the workshop's sake, let us consider April, 2021 as the cut off date for the first wave and second waves of COVID-19 in Kerala.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- mortality_df |> \n   mutate(wave = if_else(date_of_death <= \"2021-04-01\", \n                        \"First Wave\", \n                        \"Second Wave\"))  \n```\n:::\n\n\n\n\n\nLet us create `age_group` variable\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df <- mortality_df |> mutate(age_group = case_when(\n  age < 60 ~ \"<60 Years\", TRUE ~ \">60 Years\"))\n```\n:::\n\n\n\n\nDistribution of Age and Gender\n\nLets look at the distribution age and sex among COVID-19 deaths in Kerala\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> pull(age) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      0      59      68      67      76     121 \n```\n\n\n:::\n\n```{.r .cell-code}\nmortality_df |> pull(sex) |> factor() |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Male Female \n 12777   8832 \n```\n\n\n:::\n\n```{.r .cell-code}\nmortality_df |> group_by(sex) |> summarize(mean(age), sd(age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  sex    `mean(age)` `sd(age)`\n  <fct>        <dbl>     <dbl>\n1 Male          66.3      13.6\n2 Female        68.0      14.2\n```\n\n\n:::\n:::\n\n\n\n\nUsing `gtsummary`\n\n\n\n\n\n```{.r .cell-code}\nlibrary(gtsummary)\nage_sex_table <- mortality_df |>\n  dplyr::select(age, sex) |>  \n  tbl_summary(by = sex) |> \n  add_p()\n\n# using the {gt} package\nas_gt(age_sex_table) |> gt::as_latex()\n```\n\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{lccc}\n\\toprule\n\\textbf{Characteristic} & \\textbf{Male}, N = 12,777\\textsuperscript{\\textit{1}} & \\textbf{Female}, N = 8,832\\textsuperscript{\\textit{1}} & \\textbf{p-value}\\textsuperscript{\\textit{2}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nage & 68 (58, 75) & 70 (60, 78) & <0.001 \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\textsuperscript{\\textit{1}}Median (IQR)\\\\\n\\textsuperscript{\\textit{2}}Wilcoxon rank sum test\\\\\n\\end{minipage}\n\n\n\n\n\nUsing the inline R code you can:\n\n\n\n\n::: {.cell}\n\n```{.md .cell-code}\nThe median (IQR) age (in years) among males and females are \n`r inline_text(age_sex_table, variable = age, \ncolumn = \"Male\")` \nand `r inline_text(age_sex_table, \nvariable = age, column = \"Female\"), respectively.\n```\n:::\n\n\n\n\nOutput:\n\nThe median (IQR) age (in years) among males and females are 68 (58, 75) and 70 (60, 78) , respectively.\n\nVisualize using `ggplot2`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> \n  ggplot(aes(x = sex, y = age)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](quarto_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n\nDistribution of Age groups and Waves\n\n\n\n\n\n```{.r .cell-code}\nage_group_wave_table <- mortality_df |> \n  dplyr::select(age_group, wave) |>  \n  tbl_summary(by = wave) |> \n  add_p()\n\n# using the {gt} package\nas_gt(age_group_wave_table) |> gt::as_latex()\n```\n\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{lccc}\n\\toprule\n\\textbf{Characteristic} & \\textbf{First Wave}, N = 4,518\\textsuperscript{\\textit{1}} & \\textbf{Second Wave}, N = 17,091\\textsuperscript{\\textit{1}} & \\textbf{p-value}\\textsuperscript{\\textit{2}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nage\\_group &  &  & <0.001 \\\\ \n    <60 Years & 1,079 (24\\%) & 4,624 (27\\%) &  \\\\ \n    >60 Years & 3,439 (76\\%) & 12,467 (73\\%) &  \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\textsuperscript{\\textit{1}}n (\\%)\\\\\n\\textsuperscript{\\textit{2}}Pearson's Chi-squared test\\\\\n\\end{minipage}\n\n\n\n\n\n\nUsing the inline R code you can:\n\n\n\n\n::: {.cell}\n\n```{.md .cell-code}\nThe number of deaths in the First wave and Second wave of COVID-19 are  \n`r inline_text(age_group_wave_table, variable = age_group, \nlevel = \"<60 Years\", column = \"First Wave\")` and \n`r inline_text(age_group_wave_table, variable = age_group, \nlevel = \">60 Years\", column = \"Second Wave\")` , respectively.\n```\n:::\n\n\n\n\nOutput:\n\nThe number of deaths in the First wave and Second wave of COVID-19 are  1,079 (24%) and\n12,467 (73%) , respectively.\n\n\nVisualize using `ggplot2`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality_df |> \n  ggplot(aes(x = wave, fill = age_group)) +\n  geom_bar(position = \"dodge\")\n```\n\n::: {.cell-output-display}\n![](quarto_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\nLets make more sense from this plot with some `mutate()` magic again..\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- mortality_df |> \n  count(wave, age_group) |> \n  na.omit() |> \n  group_by(wave) |> \n  mutate(prop = (n / sum(n))*100) |> \n  ungroup()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  ggplot(aes(x = wave, y = prop,  fill = age_group)) +\n  geom_bar(position = \"dodge\", stat = \"identity\")\n```\n\n::: {.cell-output-display}\n![](quarto_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\nNow let us render this!\n\n\n## Conclusion\n\n\n* Quarto is awesome. \n    * The ratio of markup to content is excellent. \n    * For exploratory analyses, blog posts, and interactive documents\n    * For journal articles, though knowledge on \\LaTeX will  be helpful.\n\n* The RStudio team have made the whole process very user friendly.\n    * RStudio provides useful short cut keys for compiling to HTML, and running code chunks. \n    * These shortcut keys are presented in a clear way.\n    * Code completion on R code chunk options is really helpful. See also [chunk options documentation on the knitr website](http://yihui.name/knitr/options).\n    \n\n<!-- Other recent posts on Quarto include those by : -->\n\n<!--   [Hello Quarto | mine çetinkaya-rundel](https://mine.quarto.pub/hello-quarto/) -->\n\n<!--   [Quarto in Two Hours | Tom Mock](https://jthomasmock.github.io/quarto-2hr-webinar/materials/01-intro-quarto.html) -->\n\n",
    "supporting": [
      "quarto_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}